# Homework Lecture 3

### 1.0 Setup

In [1]:
# import Python packages
%matplotlib inline  
import pandas as pd 
import numpy as np  
import scipy as sp
from scipy import stats
import matplotlib.pyplot as plt
from functools import reduce
plt.rcParams["figure.figsize"] = [10,8]  # Set default figure size

### 1.1 Data

To change things up, I downloaded a house price data set from [Kaggle.com](https://www.kaggle.com/ "Kaggle.com"). Kaggle regularly hosts machine learning competitions and also offers many free data sets provided by the community. For this lecture I chose the [Melbourne Housing Market](https://www.kaggle.com/anthonypino/melbourne-housing-market?select=Melbourne_housing_FULL.csv "Kaggledta.com") dataset. You can find a detailed description of it by clicking the link.

In [2]:
# read in the Melbourne Housing data set
housing_raw = pd.read_csv('Melbourne_housing_FULL.csv')

Let's select a subset of a couple of variables.

In [3]:
# select a subset of variables
housing = housing_raw[['Price','Rooms','Bedroom2','Bathroom','Car','Landsize','Distance','YearBuilt'
                       ,'Lattitude','Longtitude']]

# drop rows with missing values
housing = housing.dropna()
housing

,Price,Rooms,Bedroom2,Bathroom,Car,Landsize,Distance,YearBuilt,Lattitude,Longtitude
2,1035000.0,2,2.0,1.0,0.0,156.0,2.5,1900.0,-37.80790,144.99340
4,1465000.0,3,3.0,2.0,0.0,134.0,2.5,1900.0,-37.80930,144.99440
6,1600000.0,4,3.0,1.0,2.0,120.0,2.5,2014.0,-37.80720,144.99410
11,1876000.0,3,4.0,2.0,0.0,245.0,2.5,1910.0,-37.80240,144.99930
14,1636000.0,2,2.0,1.0,2.0,256.0,2.5,1890.0,-37.80600,144.99540
...,...,...,...,...,...,...,...,...,...,...
34847,500000.0,3,3.0,2.0,2.0,383.0,25.5,2016.0,-37.61940,145.03951
34849,570000.0,3,3.0,2.0,2.0,404.0,25.5,2012.0,-37.61031,145.03393
34853,888000.0,2,2.0,2.0,1.0,98.0,6.3,2018.0,-37.81551,144.88826
34854,705000.0,2,2.0,1.0,2.0,220.0,6.3,2000.0,-37.82286,144.87856
34856,1020000.0,2,2.0,1.0,0.0,250.0,6.3,1930.0,-37.81810,144.89351

### 1.2 Bootstrap

Recall that we built a nice "OLS" class last week that allows us to conduct OLS regressions and produces regression output for any data we want. Instead of writing code from scratch, let's simply add a bootstrap option to it.

In [4]:
class OLS:

    """
    This code implements a simple OLS regression. The inputs Y and X must be in numpy matrix format. 
    """
    
    def __init__(self, Y, X):
        #Initialize the dependent and independent variables
        self.Y, self.X = Y, X 
        
        # terminate and produce error message, if Y or X are of wrong type
        if isinstance(X,np.ndarray) == False:
            raise TypeError('X is not a numpy ndarray!')
        if isinstance(Y,np.ndarray) == False:
            raise TypeError('Y is not a numpy ndarray!')
    
    # here I moved the actual regression into its own function to streamline the bootstrap code
    def get_betas(self, YY, XX):
        
        #Estimate the beta coefficients
        return np.linalg.inv(XX.T @ XX) @ (XX.T @ YY)
    
    
    def estimate(self, se_method = 'standard', B = 1000):
        
        #unpack Y and X
        Y, X = self.Y, self.X
        
        # If not input is given, we simply use standard standard errors. It is useful to also print a message to 
        # to make users aware of the standard_errors used
        print("Standard Errors computed using method:", se_method)
        
        # run the OLS regression by calling the get_betas() function
        self.beta = self.get_betas(Y, X)
        
        # ------------------------------------------------------------------------------------------------------
        
        if se_method == 'standard':
            #compute the regression residuals
            eps = Y - X @ self.beta
        
            #compute the residual variance
            s_hat = 1/(Y.shape[0] - self.beta.shape[0]) * eps.T @ eps
            
            #compute the standard errors
            self.se = np.sqrt(np.diag(np.linalg.inv(X.T @ X) * s_hat.item())).reshape((self.beta.shape[0],1))
            
            #compute confidence intervals
            CI_upper = self.beta + stats.norm.ppf(0.975)*self.se
            CI_lower = self.beta - stats.norm.ppf(0.975)*self.se
        
        elif se_method == 'bootstrap':
            print("Number of Bootstrap samples:", B)
            
            # initialize the array of bootstrap estimates
            self.bootstrapbeta = np.empty([self.beta.shape[0],B])
            
            # compute the coefficients over the bootstrap sample
            for i in range(B):
                
                # generate a vector of randomly drawn indices with replacement
                random_indices = np.random.choice(Y.shape[0], size=Y.shape[0], replace=True)
                
                # select the corresponding rows of Y and X
                Y_b = Y[random_indices]
                X_b = X[random_indices]
                
                # compute the regression coefficients for the bootstrap samples
                beta = self.get_betas(Y_b, X_b)
                
                # collect all bootstrap coefficients
                self.bootstrapbeta[:,i] = beta.ravel()
                
            # compute bootstrap standard errors
            self.se = np.sqrt(np.mean(np.square(self.bootstrapbeta-self.beta),axis=1)).reshape((self.beta.shape[0],1))
        
            #compute the bootstrap confidence intervals
            CI_upper = self.beta + 2*self.se
            CI_lower = self.beta - 2*self.se
        
        # ------------------------------------------------------------------------------------------------------
        
        #compute t-statistic for standard hypothesis test
        t = np.abs(self.beta/self.se)

        #compute p-values for standard hypothesis test
        p_vals = 2*(1-stats.norm.cdf(np.abs(t)))
        
        #generate an output table
        outmat = np.concatenate((self.beta,self.se,t,p_vals,CI_lower,CI_upper),axis=1)
        table = pd.DataFrame(outmat)
        table.columns =['beta', 'se','t-statistic','p-value','CI - lower','CI - upper'] 
        
        return table
    
    def hypothesis_test(self,i,Î²_0):
        # here a small if statement tests whether estimates have been computed before. If not, we simply call the
        # "estimate" function of our class
        if hasattr(self, 'beta'):
            beta, se = self.beta, self.se
            print("Previous estimates available. Hypothesis test is conducted based on previous estimates.")
        else:
            self.estimate()
            beta, se = self.beta, self.se
            print("No previous estimates available. Estimating OLS to obtain coefficients.")
        
        
        # compute the test statistic
        t = np.abs((beta[i] - Î²_0)/se.T[i])
        
        #compute p-values
        p_vals = 2*(1-stats.norm.cdf(np.abs(t)))
        
        # create output table
        outmat = np.concatenate((t,p_vals),axis=1)
        table = pd.DataFrame(outmat)
        table.columns =['t-statistic','p-value']
        
        return table

Having extended the functionality of our OLS class in such a way, we can again specify OLS objects and call OLS class functions on them. In our case, this allows us to easily compute standard errors in standard fashion or using bootstrap. Given that we also specified default input arguments and have the class print messages, it is also fairly robust to user error. 

Let's now use it on our house price dataset:

In [5]:
# generate the Y, and X matrices
Y = np.asarray([housing.Price]).T
X = np.asarray(housing.iloc[:,1:])

# add a constant to the independent variables
X = np.hstack((np.ones([X.shape[0],1]), X))

In [6]:
# define the house price regression object
HP_reg = OLS(Y,X)

In [7]:
# estimate a regression with standard standard errors
HP_reg.estimate()

Standard Errors computed using method: standard

,beta,se,t-statistic,p-value,CI - lower,CI - upper
0,-1.542411e+08,5.662622e+06,27.238469,0.000000e+00,-1.653397e+08,-1.431426e+08
1,2.187334e+05,1.770405e+04,12.354990,0.000000e+00,1.840341e+05,2.534327e+05
2,2.218366e+04,1.775590e+04,1.249369,2.115303e-01,-1.261726e+04,5.698457e+04
3,2.742361e+05,8.392414e+03,32.676667,0.000000e+00,2.577873e+05,2.906849e+05
4,6.902475e+04,5.082994e+03,13.579547,0.000000e+00,5.906226e+04,7.898723e+04
5,3.050285e+01,4.093579e+00,7.451389,9.237056e-14,2.247958e+01,3.852611e+01
6,-3.415782e+04,7.586077e+02,45.026992,0.000000e+00,-3.564467e+04,-3.267098e+04
7,-4.969205e+03,1.338045e+02,37.137808,0.000000e+00,-5.231457e+03,-4.706953e+03
8,-1.269495e+06,5.312626e+04,23.895812,0.000000e+00,-1.373621e+06,-1.165370e+06
9,8.011514e+05,4.103273e+04,19.524693,0.000000e+00,7.207288e+05,8.815741e+05

In [8]:
# estimate a regression with bootstrap standard errors (here I use the default bootstrap sample size)
HP_reg.estimate('bootstrap')

Standard Errors computed using method: bootstrap
Number of Bootstrap samples: 1000

,beta,se,t-statistic,p-value,CI - lower,CI - upper
0,-1.542411e+08,5.844939e+06,26.388838,0.000000e+00,-1.659310e+08,-1.425513e+08
1,2.187334e+05,3.402177e+04,6.429217,1.282625e-10,1.506898e+05,2.867769e+05
2,2.218366e+04,3.242342e+04,0.684186,4.938576e-01,-4.266319e+04,8.703050e+04
3,2.742361e+05,1.426267e+04,19.227551,0.000000e+00,2.457108e+05,3.027614e+05
4,6.902475e+04,6.496881e+03,10.624290,0.000000e+00,5.603099e+04,8.201851e+04
5,3.050285e+01,6.281994e+00,4.855599,1.200233e-06,1.793886e+01,4.306683e+01
6,-3.415782e+04,1.071887e+03,31.866999,0.000000e+00,-3.630160e+04,-3.201405e+04
7,-4.969205e+03,2.938179e+02,16.912535,0.000000e+00,-5.556841e+03,-4.381569e+03
8,-1.269495e+06,4.987962e+04,25.451182,0.000000e+00,-1.369254e+06,-1.169736e+06
9,8.011514e+05,3.807761e+04,21.039961,0.000000e+00,7.249962e+05,8.773067e+05

In this example, bootstrap does not change our conclusion regarding statistical significance. 

### 1.3 Cross-Validation

Let us again write a small function that operates on our class and does CV for us. For k-fold cross-validation, we always use k-1 chunks as training data and the 1 data chunk as testing data set.

In [9]:
def CV_OLS(Y, X, k = 10):
    # generate arrays containing the indices of the k data chunks
    ids = list(range(len(Y)))
    chunks = np.asarray(np.array_split(np.array(ids),k))
        
    # read out the sample size
    n = list(range(len(Y)))
    
    # convert k into a list
    a = np.arange(k)
    
    # initialize out-of-sample and in-sample loss
    D_oos = []
    D_is = []
    MSE_oos = []
    MSE_is = []
    R2_oos = []
    R2_is = []
    
    
    # iterate over the folds to compute the CV standard error
    for i in a:
        
        # obtain the indeces of the data belonging to the training sample
        b_train = a[np.arange(len(a))!=i]
        subid_train = np.concatenate( chunks[b_train], axis=0 )
        
        # obtain the indices of the data belonging to the test sample
        b_test =  a[np.arange(len(a)) ==i]
        subid_test = np.concatenate( chunks[b_test], axis=0 )
        
        # devide the data into test and training samples
        Y_train = Y[subid_train]
        X_train = X[subid_train,:]
        Y_test = Y[subid_test]
        X_test = X[subid_test,:]
        
        # use the OLS class to estimate the parameters on the training sample
        estimate_train = OLS(Y_train,X_train)
        estimate_train.estimate()

        # compute the out-of-sample error
        error_oos = Y_test - X_test @ estimate_train.beta
        
        # compute the in-sample error
        error_is = Y_train - X_train @ estimate_train.beta

        # compute DOOS
        D_oos.append(np.sum(np.square(error_oos),axis=0))
        D_is.append(np.sum(np.square(error_is),axis=0))
            
        # compute MSE
        MSE_oos.append(np.mean(np.square(error_oos),axis=0))
        MSE_is.append(np.mean(np.square(error_is),axis=0))
        
        # compute R^2
        R2_oos.append(1 - MSE_oos[-1]/np.var(Y_test))
        R2_is.append(1 - MSE_is[-1]/np.var(Y_train))

        
    # compute the expected out-of-sample and in-sample loss for Deviance 
    E_D_oos = np.mean(D_oos)
    E_D_is = np.mean(D_is)
    
    # compute the expected out-of-sample and in-sample loss for MSE
    E_MSE_oos = np.mean(MSE_oos)
    E_MSE_is = np.mean(MSE_is)

    # compute the expected out-of-sample and in-sample loss for R2
    E_R2_oos = np.mean(R2_oos)
    E_R2_is = np.mean(R2_is)
    
    # compute the CV standard errors for Deviance
    se_D_oos = np.sqrt(np.var(D_oos,ddof=1))
    se_D_is  = np.sqrt(np.var(D_is,ddof=1))
    
    # compute the CV standard errors for Deviance
    se_MSE_oos = np.sqrt(np.var(MSE_oos,ddof=1))
    se_MSE_is  = np.sqrt(np.var(MSE_is,ddof=1))
    
    # compute the CV standard errors for Deviance
    se_R2_oos = np.sqrt(np.var(R2_oos,ddof=1))
    se_R2_is  = np.sqrt(np.var(R2_is,ddof=1))
    
    
    # create output table
    names = [np.array(['in-sample', 'in-sample', 'in-sample', 'out-of-sample', 'out-of-sample', 'out-of-sample']),
              np.array(['Deviance','MSE','R2','Deviance','MSE','R2'])]
    outmat = [[E_D_is,se_D_is],[E_MSE_is,se_MSE_is], [E_R2_is,se_R2_is],
             [E_D_oos,se_D_oos],[E_MSE_oos,se_MSE_oos], [E_R2_oos,se_R2_oos]]
    table = pd.DataFrame(outmat,index=names)
    table.columns =['$\hat{e}$','$se(\hat{e})$'] 
    
    # return table as output
    return table

In [10]:
%%capture
# use a cell magic to supress output from the OLS.estimate() class

# run cross-validation
out = CV_OLS(Y,X,10)

In [11]:
# print the output   
out

                           $\hat{e}$  $se(\hat{e})$
in-sample     Deviance  1.903003e+15   4.739279e+13
              MSE       2.021654e+11   5.034502e+09
              R2        5.566360e-01   7.487237e-03
out-of-sample Deviance  2.138766e+14   4.739170e+13
              MSE       2.044899e+11   4.530461e+10
              R2        5.411131e-01   6.618815e-02

Looking at the $R^2$, we can see that the out-of-sample fit is slightly worse. With our regression, we can explain 56% of in-sample variation and 54% of out-of-sample variation.